apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: test-container
      image: mysql:latest
      envFrom:
      - configMapRef:
          name: datos-mysql-env
  restartPolicy: Never
