apiVersion: v1
kind: Service
metadata:
  name: heroes-svc
  labels:
     app: heroes
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30012
    protocol: TCP
  selector:
     app: heroes
       

